name: digitallibrary
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  animated_splash_screen: 1.3.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  flutter_rating_bar: 4.0.1
  flutter_zoom_drawer: 3.1.1
  get: 4.6.6
  get_storage: 2.1.1
  google_fonts: 6.1.0
  http: 1.2.0
  image_gallery_saver: 2.0.3
  nb_utils: 6.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  provider: 6.1.1
  qr_flutter: 4.1.0
  readmore: 2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoH.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logoH.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logoH.png"
    icon_size: 39
  remove_alpha_ios: true

flutter:
  assets:
    - assets/images/
    - assets/images/logoP.png
    - assets/images/logoH.png
    - assets/images/bg.png
    - assets/images/bg2.png
    - assets/images/bgL.png
    - assets/images/bgLL.png
    - assets/images/bgLLL.png
    - assets/images/cover.jpg
    - assets/images/cover2.jpeg
    - assets/images/cover3.jpeg
    - assets/images/garis.png
    - assets/images/profile.png
    - assets/images/list.png
    - assets/images/library.png
    - assets/images/home.png
    - assets/images/saved.png
    - assets/images/logout.png
  uses-material-design: true
